services:
  pomodoro-postgres:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pomodoro"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pomodoro
    volumes:
      - ../_data/postgresql:/var/lib/postgresql
    networks:
      - pomodoro_network

  pomodoro-backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      pomodoro-postgres:
        condition: service_healthy
    networks:
      - pomodoro_network
    volumes:
      - ../backend:/usr/app
  
  pomodoro-frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - pomodoro-backend
    volumes:
      - .:/usr/app

networks:
  pomodoro_network: